name: Folio
options:
  bundleIdPrefix: com.folio
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.2"
  generateEmptyDirectories: true
  knownRegions:
    - en
    - zh-Hans

packages:
  swift-markdown:
    url: https://github.com/apple/swift-markdown.git
    from: "0.5.0"
  Nuke:
    url: https://github.com/kean/Nuke.git
    from: "12.8.0"
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess.git
    from: "4.2.2"

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""

targets:
  Folio:
    type: application
    platform: iOS
    sources:
      - path: Folio
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.folio.app
        INFOPLIST_FILE: Folio/Info.plist
        GENERATE_INFOPLIST_FILE: true
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_ENTITLEMENTS: Folio/Folio.entitlements
    entitlements:
      path: Folio/Folio.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.folio.app
        com.apple.developer.applesignin:
          - Default
        aps-environment: development
    dependencies:
      - target: ShareExtension
      - package: swift-markdown
        product: Markdown
      - package: Nuke
        product: Nuke
      - package: Nuke
        product: NukeUI
      - package: KeychainAccess

  ShareExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: ShareExtension
        excludes:
          - "**/.DS_Store"
      - path: Folio/Domain/Models
      - path: Folio/Data/SwiftData/DataManager.swift
      - path: Folio/Data/SwiftData/SharedDataManager.swift
      - path: Folio/Presentation/Components/Spacing.swift
      - path: Folio/Presentation/Components/Typography.swift
      - path: Folio/Presentation/Components/CornerRadius.swift
      - path: Folio/Presentation/Components/FolioButton.swift
      - path: Folio/Presentation/Components/ReadingFontFamily.swift
      - path: Folio/Utils/Extensions/Color+Folio.swift
    resources:
      - path: Folio/Resources/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.folio.app.share-extension
        INFOPLIST_FILE: ShareExtension/Info.plist
        GENERATE_INFOPLIST_FILE: true
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        CODE_SIGN_ENTITLEMENTS: ShareExtension/ShareExtension.entitlements
    entitlements:
      path: ShareExtension/ShareExtension.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.folio.app

  FolioTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: FolioTests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: Folio
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.folio.app.tests
        GENERATE_INFOPLIST_FILE: true

schemes:
  Folio:
    build:
      targets:
        Folio: all
        ShareExtension: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - FolioTests
    archive:
      config: Release
